#cloud-config
ssh_authorized_keys:
 - ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA2to11chtn1jz3caGoRAHCRLzdFqkjz8wsRSZ3D7EqdSVYH25M5h4sxrtriitqQ0NXUc923AFkap+oa/oOPlfP9NpK20fKjXZp8DWE2jVxJ3UyIJpQQ2N4/rrVMRwb2UnGVl6UQ55dzInJZSK/RBb/q2ooJaA2uzWkxZoZeQY7jXoRcvmxkI/zk1SCDVqVFgUc9/qgjbEizW0JCJ6VX3G+cr8Jn4b4JWM8pZoJeWp89LSE4thzyJmm9EWGU3G5zrNY8X2xLJC+9zgWntbGNR8dCDpTCjjDvMacHQwIR7NkVLCE+IHwDT9rGu+IMsDSnFtdIHGVAscyC4TVz86ZUEhbQ== jigkoxsee@IONIZATION

hostname: coremaster.soup.ce.kmitl.ac.th

coreos:
  etcd2:
    name: master
    initial-advertise-peer-urls: http://192.168.122.43:2380
    initial-cluster-token: k8s_etcd
    initial-cluster: master=http://192.168.122.43:2380
    initial-cluster-state: new
    listen-peer-urls: http://192.168.122.43:2380,http://192.168.122.43:7001
    listen-client-urls: http://0.0.0.0:2379,http://0.0.0.0:4001
    advertise-client-urls: http://192.168.122.43:2379,http://192.168.122.43:4001
  fleet:
    metadata: role=master
  units:
    - name: systemd-networkd.service
      command: stop
    - name: 00-ens3.network
      runtime: true
      content: |
        [Match]
        Name=ens3

        [Network]
        Address=192.168.122.43/24
        Gateway=192.168.122.1
    - name: down-interfaces.service
      command: start
      content: |
        [Service]
        Type=oneshot
        ExecStart=/usr/bin/ip link set ens3 down
        ExecStart=/usr/bin/ip addr flush dev ens3
    - name: etcd2.service
      command: start
    - name: fleet.service
      command: start
    - name: flanneld.service
      command: start
      drop-ins:
        - name: 50-network-config.conf
          content: |
            [Unit]
            Requires=etcd2.service
            [Service]
            ExecStartPre=/usr/bin/etcdctl set /coreos.com/network/config '{"Network": "10.10.0.0/16", "Backend": {"Type": "vxlan"}}'
    - name: docker.service
      command: start
      drop-ins:
        - name: 50-insecure-registry.conf
          content: |
            [Unit]
            Requires=flanneld.service
            After=flanneld.service
            [Service]
            Environment=DOCKER_OPTS='--insecure-registry="0.0.0.0/0"'

write_files:
 - path: /etc/resolv.conf
   permissions: 0644
   owner: root
   content: |
     search soup.ce.kmitl.ac.th
     nameserver 161.246.70.75
 - path: /opt/bin/wupiao
   permissions: '0755'
   content: |
      #!/bin/bash
      # [w]ait [u]ntil [p]ort [i]s [a]ctually [o]pen
      [ -n "$1" ] && \
        until curl -o /dev/null -sIf http://${1}; do \
          sleep 1 && echo .;
        done;
      exit $?
