#cloud-config
ssh_authorized_keys:
 - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDyS+f8gcGpLrxvM5v4Ro0VNYnhdC6/48HEPX5oUigTviilB/nMC/f8r05MJ4GpWO0dAq2FVEjt1EdQ3hu+9Pviu2h7Zj3EX/qkud7RbodttMOsL5QGhDYzWMlbFIqCyaOKS0vuo1Ex/G4dBdt2P3rNFnDozAiz6RQvxupBrE7b/ZhHze6VUwF3NSqCYoUpBDrmeSHgRGse6JmoINWpJOUd2nDECn/v8jiUisKPf3lTOXyti4sQL3kCJERAaj4T/WESa2LtAu9lskJ8GzUPcimv7XcZq/yzkFsCcU0/mHEydQrlS/n9afgZaPHPEpu/GuRIiVGKwsjSRK7jtgQHkUQL ionization@hp2.soup.ce.kmitl.ac.th

hostname: core.soup.ce.kmitl.ac.th

coreos:
  etcd2:
    name: master
    initial-advertise-peer-urls: http://192.168.122.90:2380
    initial-cluster-token: k8s_etcd
    initial-cluster: master1=http://192.168.122.90:2380
    initial-cluster-state: new
    listen-peer-urls: http://192.168.122.90:2380,http://192.168.122.90:7001
    listen-client-urls: http://0.0.0.0:2379,http://0.0.0.0:4001
    advertise-client-urls: http://192.168.122.90:2379,http://192.168.122.90:4001
  fleet:
    metadata: role=master
  units:
    - name: 00-ens3.network
      runtime: true
      content: |
        [Match]
        Name=ens3

        [Network]
        Address=192.168.122.90/24
    - name: etcd2.service
      command: start
    - name: fleet.service
      command: start
    - name: flanneld.service
      command: start
      drop-ins:
        - name: 50-network-config.conf
          content: |
            [Unit]
            Requires=etcd2.service
            [Service]
            ExecStartPre=/usr/bin/etcdctl set /coreos.com/network/config '{"Network": "10.10.0.0/16", "Backend": {"Type": "vxlan"}}'
    - name: docker.service
      command: start
      drop-ins:
        - name: 50-insecure-registry.conf
          content: |
            [Unit]
            Requires=flanneld.service
            After=flanneld.service
            [Service]
            Environment=DOCKER_OPTS='--insecure-registry="0.0.0.0/0"'

write_files:
 - path: /etc/resolv.conf
   permissions: 0644
   owner: root
   content: |
     search soup.ce.kmitl.ac.th
     nameserver 192.168.122.1
     nameserver 161.246.4.3
 - path: /opt/bin/wupiao
   permissions: '0755'
   content: |
      #!/bin/bash
      # [w]ait [u]ntil [p]ort [i]s [a]ctually [o]pen
      [ -n "$1" ] && \
        until curl -o /dev/null -sIf http://${1}; do \
          sleep 1 && echo .;
        done;
      exit $?
